blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/VladimirIvaniuk/learn-python-roadmap-platform/discussions
    about: Please ask usage and design questions in Discussions.
